AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an AWS VPC with public and private subnets spread over two availability zones.

Parameters:
  EnvironmentName:
    Description: Please enter an environment name to identify each stack resource
    Type: String
  
  CIDRBlockVPC:
    Description: Please enter the CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16

  CIDRBlockPub1:
    Description: Please enter the CIDR block for the public subnet in the first AZ
    Type: String
    Default: 10.0.0.0/24

  CIDRBlockPub2:
    Description: Please enter the CIDR block for the public subnet in the second AZ
    Type: String
    Default: 10.0.4.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CIDRBlockVPC
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
 
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref CIDRBlockPub1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ1)

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref CIDRBlockPub2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ2)

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

