AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a VPC with public web server, private app server, and private database server subnets,
  spread over two Availability Zones. Also creates an Internet Gateway, one NAT Gateway for each AZ, separate
  Route Tables for the public and private subnets, and seaparate Security Groups for the web, app, and database servers.

Metadata:
  License: Apache License, Version 3.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - EnvironmentName
          - AvailabilityZones
          - NumberOfAZs
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCIDR
          - CreatePublicSubnets
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - CreatePrivateSubnets
          - CreateNATGateways
          - PrivateSubnet1ACIDR
          - PrivateSubnet2ACIDR
          - CreateAdditionalPrivateSubnets
          - PrivateSubnet1BCIDR
          - PrivateSubnet2BCIDR
          - VpcTenancy
      - Label:
          default: VPC Flow Logs Configuration
        Parameters:
          - CreateVpcFlowLogsToCloudWatch
          - VpcFlowLogsLogFormat
          - VpcFlowLogsLogGroupRetention
          - VpcFlowLogsMaxAggregationInterval
          - VpcFlowLogsTrafficType
          - VpcFlowLogsCloudWatchKMSKey
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      CreateAdditionalPrivateSubnets:
        default: Create additional private subnets
      CreateNATGateways:
        default: Create NAT gateways
      CreatePrivateSubnets:
        default: Create private subnets
      CreatePublicSubnets:
        default: Create public subnets
      CreateVPCFlowLogsToCloudWatch:
        default: Create VPC flow logs (CloudWatch)
      EnvironmentName:
        default: Envronment Name
      NumberOfAZs:
        default: Number of Availability Zones
      PrivateSubnet1ACIDR:
        default: Private subnet 1A CIDR
      PrivateSubnet1BCIDR:
        default: Private subnet 1B with dedicated network ACL CIDR
      PrivateSubnet2ACIDR:
        default: Private subnet 2A CIDR
      PrivateSubnet2BCIDR:
        default: Private subnet 2B with dedicated network ACL CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      VpcCIDR:
        default: VPC CIDR
      VpcFlowLogsCloudWatchKMSKey:
        default: CloudWatch Logs KMS key for VPC flow logs
      VpcFlowLogsLogFormat:
        default: VPC flow logs - log format
      VpcFlowLogsLogGroupRetention:
        default: VPC flow logs - log group retention
      VpcFlowLogsMaxAggregationInterval:
        default: VPC flow logs - max aggregation interval
      VpcFlowLogsTrafficType:
        default: VPC flow logs - traffic type

Parameters:
  AvailabilityZones:
    Description: Please select the Availability Zones for the subnets
    Type: List<AWS::EC2::AvailabilityZone::Name>
  CreateAdditionalPrivateSubnets:
    Type: String
    Description: Choose true to create additional private subnets with
      dedicated network ACLs in each Availability Zone. If false, the CIDR
      values for those subnets will be ignored. If true, the CreatePrivateSubnets
      parameter must also be true, as these are additional private subnets
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  CreateNATGateways:
    Type: String
    Description: Choose false when creating only private subnets. If true, both
      CreatePublicSubnets and CreatePrivateSubnets must also be true.
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  CreatePublicSubnets:
    Type: String
    Description: Choose false to create only private subnets. If false,
      CreatePrivateSubnets must be true, and the CIDR parameters for all public
      subnets will be ignored.
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  CreatePrivateSubnets:
    Type: String
    Description: Choose false to create only public subnets. If false, the CIDR parameters
      for all private subnets will be ignored.
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  CreateVPCFlowLogsToCloudWatch:
    Type: String
    Description: Choose true to create VPC flow logs for the VPC and publish them to
      CloudWatch. If false, VPC flow logs will not be created.
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  EnvironmentName:
    Description: Please enter an environment name to identify each stack resource
    Type: String
  NumberOfAZs:
    Description: Please enter the number of Availability Zones
    Type: String
    AllowedValues:
      - '1'
      - '2'
    Default: '2'
  PrivateSubnet1ACIDR:
    Description: Please enter the CIDR block for the private subnet in Availability Zone 1
    Type: String
    Default: 10.0.20.0/24
  PrivateSubnet1BCIDR:
    Description: Please enter the CIDR block for the additional private subnet in Availability Zone 1
    Type: String
    Default: 10.0.30.0/24
  PrivateSubnet2ACIDR:
    Description: Please enter the CIDR block for the private subnet in Availability Zone 2
    Type: String
    Default: 10.0.21.0/24
  PrivateSubnet2BCIDR:
    Description: Please enter the CIDR block for the additional private subnet in Availability Zone 2
    Type: String
    Default: 10.0.31.0/24
  PublicSubnet1CIDR:
    Description: Please enter the CIDR block for the public subnet in the Availability Zone 1
    Type: String
    Default: 10.0.10.0/24
  PublicSubnet2CIDR:
    Description: Please enter the CIDR block for the public subnet in the Availability Zone 2
    Type: String
    Default: 10.0.11.0/24
  VpcCIDR:
    Description: Please enter the CIDR block for the VPC
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block must be in DDN format x.x.x.x/16-28
    Default: 10.0.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnetWeb1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnetWeb1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet Web 1 (AZ1)

  PublicSubnetWeb2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PublicSubnetWeb2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet Web 2 (AZ2)

  PrivateSubnetApp1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnetApp1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet App 1 (AZ1)

  PrivateSubnetApp2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnetApp2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet App 2 (AZ2)

  PrivateSubnetDB1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnetDB1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet DB 1 (AZ1)

  PrivateSubnetDB2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnetDB2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet DB 2 (AZ2)

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnetWeb1

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnetWeb2

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Routes

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetWeb1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetWeb1

  PublicSubnetWeb2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetWeb2

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Routes (AZ1)

  DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1

  PrivateSubnetApp1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnetApp1

  PrivateSubnetDB1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnetDB1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Routes (AZ2)

  DefaultPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway2

  PrivateSubnetApp2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnetApp2

  PrivateSubnetDB2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnetDB2

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for web servers"
      GroupName: "sg-web"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for app servers"
      GroupName: "sg-web"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp *NOTE - this should be the Web Security Group - how to do it?""
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  PublicSubnetWeb1:
    Description: A reference to the public subnet for web servers in the first Availability Zone
    Value: !Ref PublicSubnetWeb1

  PublicSubnetWeb2:
    Description: A reference to the public subnet for web servers in the second Availability Zone
    Value: !Ref PublicSubnetWeb2

  PrivateSubnetApp1:
    Description: A reference to the private subnet for app servers in the first Availability Zone
    Value: !Ref PrivateSubnetApp1

  PrivateSubnetApp2:
    Description: A reference to the private subnet for app servers in the second Availability Zone
    Value: !Ref PrivateSubnetApp2

  PrivateSubnetDB1:
    Description: A reference to the private subnet for database servers in the first Availability Zone
    Value: !Ref PrivateSubnetDB1

  PrivateSubnetDB2:
    Description: A reference to the private subnet for database servers in the second Availability Zone
    Value: !Ref PrivateSubnetDB2
